ALTER TABLE users ADD COLUMN IF NOT EXISTS daily_goal INT DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS freezes_available INT DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS rank VARCHAR(30) DEFAULT 'Oyente';
